name: bierpongapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  sembast: ^3.8.5+2
  sembast_web: ^2.0.0+1
  path_provider: ^2.1.1
  uuid: ^4.2.1
  flutter_colorpicker: ^1.0.0
  flex_color_picker: ^3.7.2

dev_dependencies:
  flutter_test: { "sdk": "flutter" }
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/team_names.json
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
